flowchart LR
    Utilisateur["👤 Utilisateur / Passager"]
    
    subgraph SmartRide ["Système SmartRide"]
        direction TB
        UC1("( Rechercher & Consulter les Trajets )")
        UC2("( Réserver un Trajet )")
        UC3("( Effectuer le Paiement )")
        UC4("( Se Connecter )")

        UC2 -. "<<inclus>>" .-> UC1
        UC2 -. "<<inclus>>" .-> UC3
    end

    Auth["⚙️ <<service>>\nAuthentification"]
    IdP["🔑 Fournisseur d'Identité"]
    PaymentServ["💳 Service de Paiement"]
    AIMatching["🤖 Moteur de Matching IA"]

    Utilisateur --- UC1
    Utilisateur --- UC2
    Utilisateur --- UC4

    UC1 --- AIMatching
    UC4 --- Auth
    UC4 --- IdP
    UC3 --- PaymentServ
